### ISSUE TITLE
선생님 제 PR을 받아주세요 Prince R리 패뷸러스 히 알리아바브와

### ISSUE THREAD

**Issue by heeyawl** [dataitgirls3/TIL#31]

**Comment by ysunmi0427** [comment]
여기서 이러시면 안됩니다

**Comment by woojuj** [comment]
Prince Ali! Fabulous he!
Ali Ababwa Genuflect, show some respect
Down on one knee!

**Comment by ysunmi0427** [comment]
이보세요 여기서 이러시면 안되거든요. 희열님 PR 리뷰 확인하시고, 디렉토리 구조 바꿔주세요~
